name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Create Release Folder
      run: |
        rm -rf voltaris-calculator
        mkdir -p voltaris-calculator

    - name: Copy Files
      run: |
        cp -R assets includes templates languages *.php readme.txt voltaris-calculator/
        cp README.md voltaris-calculator/

    - name: Create ZIP
      run: |
        cd voltaris-calculator
        zip -r ../voltaris-calculator.zip .
        cd ..

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: voltaris-calculator
        path: voltaris-calculator.zip